version: '3.9'

services:
  php:
    container_name: php-notes-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./:/var/www/html/

  db:
    container_name: db-notes-project
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123

  phpmyadmin:
    container_name: notes-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db